version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fitmate_db
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_USER=fitmate_local
      - MYSQL_PASSWORD=fitmate12!
      - MYSQL_DATABASE=fitmate_local
    volumes:
      - ~/fitmate_data:/var/lib/mysql
    restart: always
